import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts/authContext";

export const metadata: Metadata = {
  title: "Todo APP by next.js/pwa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
